[linux]
srv-web.smbango.org ansible_host=192.168.1.11

[windows]
srv-win.smbango.org ansible_host=192.168.1.102

[proxy]
srv-proxy.smbango.org ansible_host=192.168.1.12

[windows:vars]
ansible_user=Administrateur
ansible_password=MOT_DE_PASSE
ansible_port=5985
ansible_connection=winrm
ansible_winrm_scheme=http
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
ansible_python_interpreter=python

[linux:vars]
ansible_user=smbango
ansible_ssh_pass=MOT_DE_PASSE
ansible_become_pass=MOT_DE_PASSE

[proxy:vars]
ansible_user=smbango
ansible_ssh_pass=MOT_DE_PASSE
ansible_become_pass=MOT_DE_PASSE

